<a href="https://colab.research.google.com/github/sofiavasqq/Vasquez_Labs/blob/main/Sofia_Vasquez_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [258]:
for i in range(100):
    print(i) #prints every numnber but 100

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [259]:
for i in range(5,8):
    print(i) #prints number between 5-8 but never 8

5
6
7


In [260]:
for i in range(3):
    print( "Test Number: " , i ) #prints every number but the number given

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [261]:
def square(x): #function always starts with def
    return x**2 #** means x squared

In [262]:
square(5) #5*5

25

In [263]:
square(square(2)) #2*2*2*2

16

In [264]:
square(square(square(2))) #2*2*2*2*2*2*2*2


256

In [265]:
square(123456) #123456*2

15241383936

In [266]:
square(square(5)) #5*5*5*5

625

In [267]:
def add_two(x):
    return x+2 #new function that adds two to whatever number you input

In [268]:
add_two(5) #5+2

7

In [269]:
square(add_two(5)) #(5*2)^2

49

### Logical Branching

In [270]:
choice = "apple" #using one equal sign means it is a assignment operator

In [271]:
if choice == "apple": #first option

    print("You choose apples.") #this is what the system will say if you choose apple

else:
    
    print("You did not choose apples.") #if apple is not chosen, it will print this.

You choose apples.


In [272]:
choice = "orange"

In [273]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.") #in this case the choice was orange so the system printed you did not choose apples

You did not choose apples.


In [274]:
choice = "apple" #using one equal sign means it is a assignment operator

In [275]:
if choice == "apple": #first option

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange": #second option/the or factor


    print("You choose oranges.")
    print("Thank you, shop again!")

else: #means you choose neither
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [276]:
choice = input("Please enter your choice (i.e. apple): ") #this is how to get input from the user

Please enter your choice (i.e. apple): apple


In [277]:
choice #you can put any choice and depending on what is inserted is ``

'apple'

In [278]:
if choice == "apple": #first option

    print("You choose apples.")

elif choice == "oranges": #second option/the or factor

    print("You choose oranges.")

else: #means you choose neither
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [279]:
np.random.random() #a branch of codes that makes up a number between 0-1

0.4950762561329112

In [280]:
np.random.random() > 0.5 #the beginning of creating the flip coin function requires some type of true or false

False

In [281]:
def flip_coin(): #when creating a function, always use (), even when you are not putting any information in
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [282]:
flip_coin() #flip coin without the images

Heads


### Graphics Output

In [283]:
from IPython.core.display import display, HTML #the blueprint 

In [284]:
display(HTML('<h1>Hello, world!</h1>')) #h1 is a heading tag

In [285]:
def coin():
  return np.random.randint(2)

In [286]:
coin()

1

In [287]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #check if the image works

In [288]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' #inputing our images into the system

In [289]:
def show_img(img):
  display(HTML('<img src=' + img + '>')) #can use this command to shrink the image

In [290]:
show_img(heads) #displays the image

In [291]:
show_img(tails) #displays the image we put for tails

In [292]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [293]:
flip_coin() #regular flip coin

In [294]:
for i in range(5):
    flip_coin() #flips the coin five different times and gives five results

In [295]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [296]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [297]:
a = np.arange(52)

In [298]:
shuffle(a) #shuffles all the cards

array([39, 14, 35,  3, 23, 25, 40, 48, 44,  0, 42,  7,  4, 13, 41, 32, 30,
       12, 31, 33,  9, 38, 37, 26,  1, 34, 27, 19, 36, 24, 43, 22,  6, 29,
       50, 15,  8, 16, 51, 46, 28, 11, 21, 49,  5, 20, 17,  2, 47, 18, 45,
       10])

In [299]:
np.random.permutation(52) #giving us the all the number 1-52 in a random order

array([32, 48, 18, 25, 45, 29, 26, 30, 35, 15, 21, 39,  2, 10, 41, 13, 44,
       11, 43, 16,  8, 40, 19,  4, 31,  7, 14, 50, 28, 22,  1, 23, 46, 42,
       37, 47, 20,  0,  9, 27, 24,  6, 38, 51,  3, 36, 17, 34,  5, 33, 12,
       49])

### Speed Test

In [300]:
%%timeit
shuffle(a)

208 µs ± 61.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [301]:
%%timeit
np.random.permutation(52) #giving us the all the number 1-52 in a random order

4.75 µs ± 1.49 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [302]:
import numpy as np #always put first

In [303]:
np.random.permutation(52) #giving us the all the number 1-52 in a random order

array([31,  7,  3, 45, 33, 13, 26, 43, 39,  6, 11, 17, 40, 25,  4, 19, 47,
       46, 29, 30, 24, 16,  0,  1, 32, 42, 23, 44,  8, 50,  9, 15, 10, 12,
        5, 27, 22, 18, 35, 38, 14, 41,  2, 49, 37, 28, 20, 21, 34, 36, 48,
       51])

In [304]:
cards = np.random.permutation(52) #giving us the all the number 1-52 in a random order

In [305]:
cards #gives us the random array

array([33, 37, 24, 28, 42, 39, 47, 31, 11, 46,  7, 43, 18, 15, 45,  1, 44,
       41, 32, 19,  0, 21,  6,  4, 23,  3, 17,  8,  9, 35, 29, 12, 51,  5,
       36, 10, 16,  2, 49, 30, 20, 34, 14, 13, 25, 38, 27, 22, 50, 40, 48,
       26])

In [306]:
cards[0] #looks at the first card on the list

33

In [307]:
cards[1] #looks at the second card on the list

37

In [308]:
cards[2]

24

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [309]:
np.arange(52).reshape(4,13) #tells the system to arrange it in 4 rows and 13 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [310]:
np.arange(52).reshape(4,13)%13 #repeats 0-12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [311]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [312]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #insert the name and types of cards
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [313]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit] #arranges the suits and names to each card

In [314]:
card_name(0) #now the system is able to label any card from the image

'Ace of Clubs'

In [315]:
card_name(51) #0 being the first and 51 being the last. this is why 52 would not.

'King of Diamonds'

In [316]:
cards = np.random.permutation(52) #giving us the all the number 1-52 in a random order

In [317]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1]) #the -1 will give us the last one in the deck, -2 would be the second one from the end, and so on 

In [318]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Clubs', 'Queen of Spades', 'Ace of Spades')

In [319]:
for i in range(5):
    print(card_name(cards[i])) #picks 5 random cards

Three of Clubs
Queen of Spades
Seven of Diamonds
Seven of Hearts
Three of Hearts


In [320]:
for i in range(15):
    print(card_name(cards[i])) #picks 15 random cards from the deck

Three of Clubs
Queen of Spades
Seven of Diamonds
Seven of Hearts
Three of Hearts
Four of Spades
Two of Spades
King of Spades
Ten of Hearts
Jack of Spades
Eight of Hearts
King of Clubs
Four of Hearts
Six of Spades
Jack of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [321]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [322]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [323]:
i = np.random.randint(4)
j = np.random.randint(13)

In [324]:
i,j

(2, 11)

In [325]:
suit[i]

's'

In [326]:
card[j]

'q'

In [327]:
from IPython.core.display import display, HTML

In [328]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [329]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [330]:
show_img(img)

In [331]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [332]:
card_image(3)

'k4'

In [342]:
img = card_url_head + card_image(3) + card_url_tail

In [343]:
show_img(img) #shows what ever card 3 is

In [336]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img) #shows all cards