<a href="https://colab.research.google.com/github/sofiavasqq/Vasquez_Labs/blob/main/Vasquez_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab #3 Notebook

#Loops

In [ ]:
for i in range(10):
    print(i) #prints every number but 10

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(3):
    print("Test Number: ",i) #prints every number but the number given

Test Number:  0
Test Number:  1
Test Number:  2


#Functions: Square

In [ ]:
def square(x):   #function always start with def 
    return x**2  #** means x squared

In [ ]:
square(5)

25

In [ ]:
square(20)

400

In [ ]:
square(123456789)

15241578750190521

In [ ]:
square(square(5)) #5*5*5*5

625

In [ ]:
square(square(square(2))) #2*2*2*2*2*2*2*2

256

In [ ]:
def add_two(x):
    return x+2 #new function that adds two to whatever number you input

In [ ]:
add_two(5)

7

In [ ]:
square(add_two(5))

49

#Strings/Logical Branching

In [ ]:
choice = "apple"  #using one equal sign means it is a assignment operator

In [ ]:
if choice == "apple":

  print("You choose apples.")

else:

  print("You did not choose apples.")

You choose apples.


In [ ]:
if choice == "apple": #first option

    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange": #second option/the or factor

    print("You choose oranges.")
    print("Thank you, shop again!")

else:  #means you choose neither

    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")      
      

You choose apples.
Thank you, shop again!


#User Input

In [ ]:
choice = input("Please eneter your choice (i.e. apple):") #this is how to get input from the user

Please eneter your choice (i.e. apple):oranges


In [ ]:
choice

'oranges'

#Permutation/Speed Test

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52) #giving us the all the number 1-52 in a random order

array([27, 31, 49, 15, 29,  4, 22, 20,  5,  9, 26, 30, 44,  8, 46, 28, 13,
       12, 50, 23, 41, 45,  2, 14, 11, 36, 17, 24, 33, 32,  6,  7, 40, 51,
       18, 43, 48, 38, 16, 25,  3,  1,  0, 21, 34, 19, 39, 35, 37, 47, 10,
       42])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards #gives us the random array

array([41,  3, 42, 11, 22, 39, 14, 37, 29, 21,  8, 32, 43, 34,  0, 19, 23,
       35, 25, 12, 30, 47, 31, 26,  9, 44, 40, 50, 45, 20, 28, 17, 24,  1,
        5, 18, 10, 13, 49, 48, 15, 33, 27,  4,  2, 38,  6, 36, 51, 46,  7,
       16])

In [ ]:
cards[0] #looks at the first card on the list

41

In [ ]:
cards[1] #looks at the second card on the list

3

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13) #tells the system to arrange it in 4 rows and 13 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 #repeats 0-12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs', 'Spades', 'Hearts', 'Diamonds']
names = ['Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Jack', 'Queen', 'King']

In [ ]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [ ]:
suits[0]

'Clubs'

In [ ]:
names[1]

'Two'

In [ ]:
def card_name(card_number):

    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck           =card_name(cards[0])
second_card_in_deck   =card_name(cards[1])
last_card_in_deck     =card_name(cards[-1]) #the -1 will give us the last one in the deck, -2 would be the second one from the end, and so on 

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Ten of Diamonds', 'Four of Clubs', 'Ten of Hearts')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

Ten of Diamonds
Four of Clubs
Seven of Clubs
Four of Hearts
Queen of Clubs


#making your own cards

In [ ]:
card_url_head = "https://www.improvemagic.com/wp.content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = [ 'k', 'p', 's', '1']
card = ['a', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'j', 'q', 'k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(3, 12)

In [ ]:
card[j]

'k'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [ ]:
show_img(img)